#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"BPSomeClass": "00_core.ipynb",
         "bp_obj": "00_core.ipynb",
         "bp_obj.attribute2": "00_core.ipynb"}

modules = ["sync.py"]

git_url = "https://github.com/x-xz/hello/tree/master/"

def custom_doc_links(name): return None